export enum PhotographyType {
  NO_TYPE = "NO_TYPE",
  OTHER = "OTHER",
  PORTRAITS = "PORTRAITS",
  WEDDING = "WEDDING",
  REAL_ESTATE = "REAL_ESTATE",
  LANDSCAPE_NATURE = "LANDSCAPE_NATURE",
  EVENTS = "EVENTS",
  FAMILY_NEWBORN = "FAMILY_NEWBORN",
  BOUDOIR = "BOUDOIR",
  SPORTS = "SPORTS",
}

export enum CropAspectRatio {
  RATIO_2X3 = "2X3",
  RATIO_4X5 = "4X5",
  RATIO_5X7 = "5X7",
}
